# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnimeQuiz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SQLite.swift'
pod 'Toast-Swift'
pod 'MBProgressHUD'
pod 'Google-Mobile-Ads-SDK' , '~> 7.69.0'
pod 'SwiftKeychainWrapper'


  # Pods for AnimeQuiz

  target 'AnimeQuizTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnimeQuizUITests' do
    # Pods for testing
  end

end
